Extend the username validation function
js-tasks-ru/jsbasic-20230302_pukhliak pull request #3
Opened 2023-03-08 13:52 UTC by Pukhliak

2023-03-08 13:53 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-03-08 14:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-03-08 14:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-03-08 14:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-03-09 11:10 UTC, SinimaWath requested changes

2023-03-09 11:10 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
Короткие условия, всегда лучше переписать на операцию с (||, && и !):
```
return Boolean(name) && str.length >= 4 && ....
```

2023-03-09 11:10 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  firstLtr = str[0];
Это не создание переменной, тут забыл let или const

2023-03-09 11:10 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  newStr = str.toLowerCase();
Это не создание переменной, тут забыл let или const

2023-03-09 11:10 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  }
`newStr.includes("1xbet") || newStr.includes("xxx")` и так уже в качестве результата возвращает true/false, поэтому нет необходимости в if`return newStr.includes("1xbet") || newStr.includes("xxx")`

2023-03-09 11:10 UTC, SinimaWath commented on 1-module/5-task/index.js
> +    newStr = str.slice(0, maxlength - 1) + "…";
Это не создание переменной, тут забыл let или const

2023-03-11 11:23 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-03-11 14:06 UTC, SinimaWath approved these changes

2023-03-11 14:06 UTC, merged